controllers/CrudController.php
<?
namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\User;
use app\models\SummingTree;


class CrudController extends Controller {
	
	public function actionIndex($parent = 0){
		User::requireLoggedIn();
		
		$provider = SummingTree::getProvider($parent);

		Yii::$app->user->setReturnUrl(Yii::$app->request->getUrl());
		
		$model = SummingTree::findByPk($parent);
		$grand = $model ? $model->parent_id : false;

		return $this->render('list', ['dataProvider'=>$provider, 'parent'=>$parent, 'grand'=>$grand]);
		
	}
	
	public function actionView($id, $parent = 0){

		User::requireLoggedIn();

		if('new' == $id){
			$model = new SummingTree();
			$model->parent_id = $parent;
		} else {
			$model = SummingTree::findByPk($id);
		}
		if(!$model)
			throw new \yii\web\NotFoundHttpException;
			
		if($model->load(Yii::$app->request->post())){
			$model->save();
			$this->goBack();
		}
			
			return $this->render('element', ['model'=>$model]);
	}

	public function actionRemove($id){
		User::requireLoggedIn();

		$model = SummingTree::findByPk($id);

		if(!$model)
			throw new \yii\web\NotFoundHttpException;

		$model->delete();
		
		$this->goBack();
		
	}
	
}

?>

views/crud/element.php
<? use yii\widgets\ActiveForm;
?>

<? $form = ActiveForm::begin();
?>

<? echo $form->field($model, 'title') ?>
<? echo $form->field($model, 'value') ?>
<button class="btn btn-primary">Save</button>

<? ActiveForm::end(); ?>

views/crud/list.php
<?
use yii\grid\GridView;
use yii\helpers\Url;
use kartik\icons\Icon;
use app\models\SummingTree;
$this->title = 'crud';
?>

<a href="<? echo Url::toRoute(['crud/view', 'parent'=>$parent, 'id'=>'new'])?>"><i class="fa fa-plus"></i></a>
<? if(false !== $grand) { ?>
<a href="<? echo Url::toRoute(['crud/index', 'parent'=>$grand])?>"><i class="fa fa-arrow-up"></i></a>
<? } ?>

<div class="sum">
	Сумма того, что выше: <? echo SummingTree::sumabove_string($parent) ?>
</div>


<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'id',
        'title',
        'value',
        [
        	'content' => function ($model){
        		return SummingTree::sumbelow_string($model->id);
        	},
        	'label' => 'Сумма того, что ниже'
    	],
        [
        	'content' => function ($model){
        		return ''.
        			'<a href="'.Url::toRoute(['crud/view', 'id'=>$model->id]).'"><i class="fa fa-edit"></i></a> '.
        			'<a href="'.Url::toRoute(['crud/index', 'parent'=>$model->id]).'"><i class="fa fa-arrow-down"></i></a> '.
        			'<a href="'.Url::toRoute(['crud/remove', 'id'=>$model->id]).'"><i class="fa fa-close"></i></a>';
        	},
        	'label' => 'Действия'
        ]
    ],
]) ?>